server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /api

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/hands
    username: root
    password: root

  jpa:
    open-in-view: false
    show-sql: true
    #    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    #      ddl-auto: none
    properties:
      hibernate:
        # sql 변수 생성 시 자동으로 ``으로 감싸준다.
        globally_quoted_identifiers: true
        # 콘솔에 뜨는 sql 보기 좋게 만들어준다.
        format_sql: true
        generate_statistics: false # 쿼리 수행 통계를 확인할 수 있다
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    org:
      hibernate:
        #        SQL: DEBUG
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
